[package]
name = "nhipd"
version = "0.1.0"
edition = "2024"
description = "Nested Hierarchical Internet Protocol (NHIP) - daemon"


[dependencies]
anyhow = "1.0.102"
aya = "0.13.1"
env_logger = "0.11.10"
log = "0.4.29"
tokio = { version = "1.52.3", features = ["macros", "rt", "rt-multi-thread", "signal", "sync"] }
bytemuck = { version = "1.25.0", features = ["derive"] }

nhip-core = { path = "../nhip-core" }
nharp = { path = "../nharp" }
nhip-cfg = { path = "../nhip-cfg" }
network-types = "0.2.0"
