[package]
name = "nhipctl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
bytemuck = { version = "1.25.0", features = ["derive"] }
aya = "0.13.1"
log = "0.4.29"

nharp = { path = "../nharp" }
nhip-core = { path = "../nhip-core" }
nhip-cfg = { path = "../nhip-cfg" }

