[package]
name = "nhipd-ebpf"
version = "0.1.0"
edition = "2024"

[dependencies]
aya-ebpf = { version = "0.1.1", default-features = false }
aya-log-ebpf = { version = "0.1.0", default-features = false }
bytemuck = { version = "1.25.0", features = ["derive"], default-features = false }
network-types = { version = "0.2.0", default-features = false }
nhip-core = { path = "../nhip/nhip-core", default-features = false }

[[bin]]
name = "nhipd-ebpf"
path = "src/main.rs"
test = false
doctest = false
bench = false